version: '3.1'

services:
#*****************Microservice-patient******************************
  microservice-patient-app:
    image: microservice-patient-image
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mediscreen-mysql
    ports:
      - "8081:8081"
#*****************Mysql for microservice patient******************************
  mediscreen-mysql:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: mediscreen
    ports:
      - "13306:3306"
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
  #*****************Adminer******************************
  adminer:
    image: adminer
    restart: always
    ports:
      - "8000:8080"
#    environment:
#        SPRING_DATASOURCE_URL: jdbc:mysql://mediscreen-mysql:3306/mediscreen?serverTimezone=Europe/Paris
#        SPRING_DATASOURCE_USERNAME: root
#        SPRING_DATASOURCE_PASSWORD: rootroot
#*****************Microservice-history-patient******************************
  microservice-history-patient-app:
    image: microservice-history-patient-image
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "8082:8082"

#*************************MongoDb for microservice-history-patient*******************
  mongo:
    image: mongo
    container_name: "mongo"
    hostname: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
        - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#*****************Mongo-express******************************
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8085:8081"
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/






